name: Sync Wiki

on:
  push:
    branches: [master]
    paths:
      - 'docs/wiki/**'
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Clone wiki repository
        run: |
          git clone "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git" wiki
      
      - name: Copy wiki files
        run: |
          # Remove old wiki files (except .git)
          find wiki -type f -not -path "wiki/.git/*" -delete
          
          # Copy new wiki files
          cp -r docs/wiki/* wiki/
          
          # Rename .md files to remove .md extension for GitHub Wiki
          cd wiki
          for file in *.md; do
            if [ -f "$file" ]; then
              mv "$file" "${file%.md}"
            fi
          done
      
      - name: Push to wiki
        run: |
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-sync from docs/wiki - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push origin master
          fi